version: 2.1

# this allows you to use CircleCI's dynamic configuration feature
setup: true

orbs:
  orb-tools: circleci/orb-tools@12.0.4
  shellcheck: circleci/shellcheck@3.1

filters: &filters
  tags:
    only: /.*/

jobs:
  command-tests:
    docker:
      - image: cimg/base:current
    steps:
      - checkout

workflows:
  # Prior to producing a development orb (which requires credentials) basic validation, linting, and even unit testing can be performed.
  # This workflow will run on every commit
  test-pack:
    jobs:
      - orb-tools/lint: # Lint Yaml files
          filters: *filters
      - orb-tools/pack: # Pack orb source
          filters: *filters
      - orb-tools/review:
          max_command_length: 140
          filters: *filters
      - shellcheck/check:
          filters: *filters
      - command-tests:
          filters:
            tags:
              only: /.*/

      - orb-tools/publish:
          name: publish_dev_test
          attach_workspace: false
          orb_name: circleci/orb-tools
          vcs_type: <<pipeline.project.type>>
          pub_type: dev
          requires:
            - orb-tools/lint
            - orb-tools/pack
            - orb-tools/review
            - shellcheck/check
            - command-tests
          context: orb-publishing

      - orb-tools/publish:
          orb_name: napoles-mk/muuktest
          attach_workspace: false
          vcs_type: << pipeline.project.type >>
          pub_type: production
          requires:
            - publish_dev_test
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/



