version: 2.1

# this allows you to use CircleCI's dynamic configuration feature
setup: true

orbs:
  orb-tools: circleci/orb-tools@12.0.4
  shellcheck: circleci/shellcheck@3.1

filters: &filters
  tags:
    only: /.*/

workflows:
  # Prior to producing a development orb (which requires credentials) basic validation, linting, and even unit testing can be performed.
  # This workflow will run on every commit
  test-pack:
    jobs:
      - orb-tools/lint: # Lint Yaml files
          filters: *filters
      - orb-tools/pack: # Pack orb source
          filters: *filters
      - orb-tools/review:
          max_command_length: 140
          filters: *filters
      - shellcheck/check:
          filters: *filters
      # Triggers the next workflow in the Orb Development Kit.
      - orb-tools/continue:
          pipeline_number: << pipeline.number >>
          vcs_type: << pipeline.project.type >>
          orb_name: napoles-mk/muuktest
          requires: [orb-tools/lint, orb-tools/pack, orb-tools/review, shellcheck/check]
          filters: *filters
          pre-steps:
            - checkout


