version: '2.1'
orbs:
  orb-tools: circleci/orb-tools@12.0.4
jobs:
  command-tests:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
workflows:
  test-deploy:
    jobs:
      - command-tests:
          filters:
            tags:
              only: /.*/
      - orb-tools/publish:
          orb_name: napoles-mk/muuktest
          vcs_type: << pipeline.project.type >>
          pub_type: production
          requires:
            - command-tests
          context: orb-publishing-context
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/