version: '2.1'
orbs:
  orb-tools: circleci/orb-tools@12.0.4

filters: &filters
  tags:
    only: /.*/

jobs:
  command-tests:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
workflows:
  test-deploy:
    jobs:
      - command-tests:
          filters:
            tags:
              only: /.*/
      - orb-tools/publish:
          name: publish_dev_test
          attach_workspace: false
          orb_name: circleci/orb-tools
          vcs_type: <<pipeline.project.type>>
          pub_type: dev
          requires:
            - command-tests
          context: orb-publishing
      - orb-tools/publish:
          orb_name: napoles-mk/muuktest
          attach_workspace: false
          vcs_type: << pipeline.project.type >>
          pub_type: production
          requires:
            - publish_dev_test
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/